In [36]:
#import files
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df= pd.read_csv(r"C:\Users\cradr\Downloads\Dataset.csv")

In [37]:
#A sneak peak of the table
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [38]:
#Understand data structures and Identify the string formats to be converted to date formats
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   str
 1   type          8790 non-null   str
 2   title         8790 non-null   str
 3   director      8790 non-null   str
 4   country       8790 non-null   str
 5   date_added    8790 non-null   str
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   str
 8   duration      8790 non-null   str
 9   listed_in     8790 non-null   str
dtypes: int64(1), str(9)
memory usage: 686.8 KB

In [39]:
#Check for Null values
df.isnull().sum

<bound method DataFrame.sum of       show_id   type  title  director  country  date_added  release_year  \
0       False  False  False     False    False       False         False
1       False  False  False     False    False       False         False
2       False  False  False     False    False       False         False
3       False  False  False     False    False       False         False
4       False  False  False     False    False       False         False
...       ...    ...    ...       ...      ...         ...           ...
8785    False  False  False     False    False       False         False
8786    False  False  False     False    False       False         False
8787    False  False  False     False    False       False         False
8788    False  False  False     False    False       False         False
8789    False  False  False     False    False       False         False

      rating  duration  listed_in
0      False     False      False
1      False     False      False
2      False     False      False
3      False     False      False
4      False     False      False
...      ...       ...        ...
8785   False     False      False
8786   False     False      False
8787   False     False      False
8788   False     False      False
8789   False     False      False

[8790 rows x 10 columns]>

In [40]:
#Change str to date-time datatype format
df['date_added']= pd.to_datetime(df['date_added'])

In [41]:
#df['release_year'] = pd.to_datetime(df['release_year'])

In [55]:
#Standardize duration column, create two more rows, duration type and duration number
df['duration_num'] = df['duration'].str.extract (r'(\d+)').astype(float)

In [56]:
df['duration_time'] = df['duration'].str.extract('([a-zA-Z]+)')

In [57]:
df[['duration','duration_time','duration_num']].head()

   duration duration_time  duration_num
0    90 min           min          90.0
1  1 Season        Season           1.0
2  1 Season        Season           1.0
3    91 min           min          91.0
4   125 min           min         125.0

In [ ]:
#Check for duplicates and inconsistensies
df.duplicated().sum()

np.int64(0)

In [74]:
df['country'].unique()
df['rating'].unique()
df['type'].unique()
df['country'].unique()
df['rating'].unique()
df['title'].unique()
df['director'].unique()

<StringArray>
[        'Kirsten Johnson',         'Julien Leclercq',
           'Mike Flanagan',           'Bruno Garotti',
            'Haile Gerima',         'Andy Devonshire',
          'Theodore Melfi',             'Suhas Kadav',
     'Christian Schwochow',               'Not Given',
 ...
 'Saratswadee Wongsomphet',       'Kirati Nakintanon',
             'Mark Risley',             'James Brown',
              'Ivona Juka',                  'Mu Chu',
 'Chandra Prakash Dwivedi',         'Majid Al Ansari',
            'Peter Hewitt',             'Mozez Singh']
Length: 4528, dtype: str

In [75]:
df['country'].unique()

<StringArray>
[       'United States',               'France',               'Brazil',
       'United Kingdom',                'India',              'Germany',
             'Pakistan',            'Not Given',                'China',
         'South Africa',                'Japan',              'Nigeria',
                'Spain',          'Philippines',            'Australia',
            'Argentina',               'Canada',            'Hong Kong',
                'Italy',          'New Zealand',                'Egypt',
             'Colombia',               'Mexico',              'Belgium',
          'Switzerland',               'Taiwan',             'Bulgaria',
               'Poland',          'South Korea',         'Saudi Arabia',
             'Thailand',            'Indonesia',               'Kuwait',
             'Malaysia',              'Vietnam',              'Lebanon',
              'Romania',                'Syria', 'United Arab Emirates',
               'Sweden',            'Mauritius',              'Austria',
               'Turkey',       'Czech Republic',             'Cameroon',
          'Netherlands',              'Ireland',               'Russia',
                'Kenya',                'Chile',              'Uruguay',
           'Bangladesh',             'Portugal',              'Hungary',
               'Norway',            'Singapore',              'Iceland',
               'Serbia',              'Namibia',                 'Peru',
           'Mozambique',                'Ghana',             'Zimbabwe',
               'Israel',              'Finland',              'Denmark',
             'Paraguay',             'Cambodia',              'Georgia',
         'Soviet Union',               'Greece',         'West Germany',
                 'Iran',            'Venezuela',             'Slovenia',
            'Guatemala',              'Jamaica',              'Somalia',
              'Croatia',               'Jordan',           'Luxembourg',
              'Senegal',              'Belarus',          'Puerto Rico',
               'Cyprus',              'Ukraine']
Length: 86, dtype: str

In [76]:
df['listed_in'].unique()

<StringArray>
[                                                'Documentaries',
 'Crime TV Shows, International TV Shows, TV Action & Adventure',
                            'TV Dramas, TV Horror, TV Mysteries',
                            'Children & Family Movies, Comedies',
              'Dramas, Independent Movies, International Movies',
                                  'British TV Shows, Reality TV',
                                              'Comedies, Dramas',
          'Children & Family Movies, Comedies, Music & Musicals',
                                  'Dramas, International Movies',
                    'Children & Family Movies, Music & Musicals',
 ...
                      'British TV Shows, Docuseries, Reality TV',
                    'Anime Series, Crime TV Shows, TV Thrillers',
        'Classic & Cult TV, Kids' TV, Spanish-Language TV Shows',
       'Romantic TV Shows, Spanish-Language TV Shows, TV Dramas',
                            'TV Action & Adventure, TV Comedies',
                    'Classic & Cult TV, TV Horror, TV Mysteries',
                                   'Crime TV Shows, TV Comedies',
                      'Classic & Cult TV, Kids' TV, TV Comedies',
                        'Classic & Cult TV, TV Sci-Fi & Fantasy',
                  'Classic & Cult TV, Crime TV Shows, TV Dramas']
Length: 513, dtype: str

In [77]:
df['director'].unique()

<StringArray>
[        'Kirsten Johnson',         'Julien Leclercq',
           'Mike Flanagan',           'Bruno Garotti',
            'Haile Gerima',         'Andy Devonshire',
          'Theodore Melfi',             'Suhas Kadav',
     'Christian Schwochow',               'Not Given',
 ...
 'Saratswadee Wongsomphet',       'Kirati Nakintanon',
             'Mark Risley',             'James Brown',
              'Ivona Juka',                  'Mu Chu',
 'Chandra Prakash Dwivedi',         'Majid Al Ansari',
            'Peter Hewitt',             'Mozez Singh']
Length: 4528, dtype: str

In [78]:
df['rating']= df['rating'].replace({'UR':'NR'})

In [79]:
df_genre= df.assign(listed_in =df['listed_in'].str.split(',')).explode('listed_in')

In [80]:
df_genre[['listed_in','title']].head(10)

                  listed_in                             title
0             Documentaries              Dick Johnson Is Dead
1            Crime TV Shows                         Ganglands
1    International TV Shows                         Ganglands
1     TV Action & Adventure                         Ganglands
2                 TV Dramas                     Midnight Mass
2                 TV Horror                     Midnight Mass
2              TV Mysteries                     Midnight Mass
3  Children & Family Movies  Confessions of an Invisible Girl
3                  Comedies  Confessions of an Invisible Girl
4                    Dramas                           Sankofa

In [86]:
df.to_csv('netflix_cleaned.csv',index=False)

In [87]:
df_genre.to_csv('netflix_genres_exploded.csv', index=False)

In [91]:
import os
print (os.listdir())

['a44adf7f53', 'bin', 'Code.exe', 'Code.VisualElementsManifest.xml', 'df53daabb1', 'Netflix_cleaned.csv', 'netflix_genres_exploded.csv', 'new_Code.exe', 'new_Code.VisualElementsManifest.xml', 'unins000.dat', 'unins000.exe', 'unins000.msg', 'updating_version']